# 빌드 구동환경 설정
# xenial: Ubuntu 16:04 LTS
language: java
jdk: openjdk11
dist: xenial
os: linux

branches:
  only:
    - master
    - develop
    # feature 서브그룹 브랜치를 정규 표현식으로 정의 ex) feature/5, feature/1
    - /^(feature)\/\w*$/

# gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시 (의존성은 최초 1회만 받도록 설정하여 반복 작업을 사전에 차단)
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# 브랜치에 푸시되었을 때 수행하는 명령어
# 프로젝트 빌드 작업 : 프로젝트 내부에 위치한 gradlew를 사용
script: "./gradlew clean assemble build"

# Travis CI 수행 완료 시 지정된 이메일로 완료 메일 발송
notifications:
  email:
    recipients:
      - dev-kimdoyoung@naver.com
      - kia0097@naver.com
      - do0ob1124@gmail.com
      - 201703ska@naver.com
